apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-minio-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.minio.requests }}
  selector:
    matchLabels:
      pv: minio-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-mysql-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.mysql.requests }}
  selector:
    matchLabels:
      pv: mysql-pv


#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: octopus-mysql-pvc
#spec:
#  accessModes: ["ReadWriteMany"]
#  storageClassName: nfs-mysql
#  resources:
#    requests:
#      storage: {{ .Values.pvc.mysql.requests }}


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-redis-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.redis.requests }}
  selector:
    matchLabels:
      pv: redis-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-influxdb-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.influxdb.requests }}
  selector:
    matchLabels:
      pv: influxdb-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-logger-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.logger.requests }}
  selector:
    matchLabels:
      pv: logger-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-sftpgo-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.pvc.sftpgo.requests }}
  selector:
    matchLabels:
      pv: sftpgo-pv

---
{{- range $key, $val := .Values.storages }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-storage{{ $key }}-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .requests }}
  selector:
    matchLabels:
      pv: storage{{ $key }}-pv
---
{{- end }}