apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openaiserver.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "openaiserver.fullname" . }}
  labels:
{{ include "openaiserver.labels" . | indent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ template "openaiserver.port" . }}
    targetPort: {{ template "openaiserver.port" . }}
  selector:
{{ include "openaiserver.select-labels" . | indent 8 }}


---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "openaiserver.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "openaiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "openaiserver.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openaiserver.fullname" . }}
  labels:
{{ include "openaiserver.labels" . | indent 4 }}
data:
  openaiserver-config.yml: |
    app:
        name: openaiserver
        version: v1.0
        isDev: false
        logLevel: {{ .Values.openaiserver.app.logLevel }}
    server:
        http:
          addr:  0.0.0.0:8001
          timeout: 60s
          jwtSecrect: asdf
         
    data:
        baseServerAddr: {{ include "baseserver.grpcServiceAddr" . }}
        baseServerRequestTimeout: 30s
        redis:
          addr: {{ include "redis.serviceAddr" . }} 
          username: {{ .Values.openaiserver.data.redis.username }}
          password: {{ .Values.openaiserver.data.redis.password }}
    service:
        port: {{ template "openaiserver.port" . }}
        targetPort: {{ template "openaiserver.port" . }}
        tokenExpirationSec: {{ .Values.openaiserver.service.tokenExpirationSec }}
        webConfig:
          logoAddr: "{{ .Values.openaiserver.service.webConfig.logoAddr }}"
          themeColor: "{{ .Values.openaiserver.service.webConfig.themeColor }}"
          systemNameEn: "{{ .Values.openaiserver.service.webConfig.systemNameEn }}"
          systemNameZh: "{{ .Values.openaiserver.service.webConfig.systemNameZh }}"
          organization: "{{ .Values.openaiserver.service.webConfig.organization }}"
          manualInvisible: {{ .Values.openaiserver.service.webConfig.manualInvisible }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openaiserver.fullname" . }}
spec:
  selector:
    matchLabels:
{{ include "openaiserver.select-labels" . | indent 8 }}
  replicas: {{ .Values.openaiserver.replicas }}
  template:
    metadata:
      labels:
{{ include "openaiserver.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "openaiserver.fullname" . }}
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: openaiserver-config
        configMap:
          name: {{ template "openaiserver.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.image.repository.address }}{{ .Values.global.image.repository.pathname }}/{{ .Values.openaiserver.image.name }}:{{ default .Chart.AppVersion .Values.openaiserver.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args: [ "-conf", "/etc/openaiserver/openaiserver-config.yml" ]
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
          - name: openaiserver-config
            mountPath: /etc/openaiserver
        ports:
        - name: {{ template "openaiserver.name" . }}
          containerPort: {{ template "openaiserver.port" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}