apiVersion: v2
name: octopus
description: A one-stop computing fusion platform for multiple computing scenarios

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: dev-1.2.36

dependencies:
- name: mysql
  version: 8.5.9
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 14.3.2
  repository: https://charts.bitnami.com/bitnami
- name: minio
  version: 7.1.3
  repository: https://charts.bitnami.com/bitnami
- name: nginx-ingress-controller
  version: 7.6.9
  repository: https://charts.bitnami.com/bitnami

home: https://octopus.openi.org.cn/
icon: https://git.openi.org.cn/OpenI/octopus/media/branch/master/logo.png
keywords:
  - ai
  - machine learning
  - deep learning
  - hpc
  - openi
maintainers:
  - email: cloudbrain_registerï¼ pcl.ac.cn
    name: Octopus
sources:
  - https://git.openi.org.cn/OpenI/octopus
  - https://octopus.openi.org.cn/