dependencies:
  - name: mysql
    version: 8.5.9
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 14.3.2
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 7.1.3
    repository: https://charts.bitnami.com/bitnami
  - name: nginx-ingress-controller
    version: 7.6.9
    repository: https://charts.bitnami.com/bitnami
  - name: influxdb
    version: 4.10.0
    repository: https://helm.influxdata.com/
  - name: seldon-core-operator
    version: 1.12.0
    repository: https://storage.googleapis.com/seldon-charts